name: CI

on:
  push:
    branches:
      - main 
  pull_request:

jobs:
  lint-and-format:
    name: Lint
    strategy:
      fail-fast: false
      matrix:
        session: [types, formatting, imports]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Lint and format
        run: |
          pip install -U pip
          pip install -r requirements.dev.txt
          nox -s ${{ matrix.session }}
