name: Build and deploy HOM

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.ORG_DOCKER_USERNAME }} -p ${{ secrets.ORG_DOCKER_PASSWORD }}

      - name: Build & Push the Docker image
        run: |
          docker build . --file dockerfile.prod --tag wiseoldman/hom:latest
          docker push wiseoldman/hom:latest

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Restart docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            cd wise-old-man
            docker image rm wiseoldman/hom
            docker-compose pull hom-bot
            docker-compose up -d --no-deps --build hom-bot
